name: trigger-book-build
on:
  pull_request:

jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name:  na-cordex-viz-cookbook-dev
      artifact_name: book-zip-${{ github.event.number }}
      binder_nb_timeout: 3600 # one hour run time
      # Other input options are possible, see ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml
